### ISSUE TITLE
ruby 2.2.0 error

### ISSUE THREAD

**Issue by will** [interagent/pliny#114]
Tried updating to 2.2.0, and got this:

```
➤ bundle exec rspec spec                                                                                                                  git:master*
/Users/will/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pliny-0.5.0/lib/pliny/config_helpers.rb:86:in `remove_const': constant Object::Config not defined (NameError)
	from /Users/will/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pliny-0.5.0/lib/pliny/config_helpers.rb:86:in `<top (required)>'
	from /Users/will/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
	from /Users/will/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /Users/will/code/heroku/telex/config/config.rb:1:in `<top (required)>'
```

**Comment by brandur** [comment]
@will +1! Our bad. See #111 for now.

**Comment by will** [comment]
Oh, I looked through the open issues before making a new one, but it was closed so I didn't see it.
